name: dio_example
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 0.0.1
homepage: https://github.com/flutterchina/dio
author: wendux <824783146@qq.com>
environment:
  sdk: '>=1.9.0 <3.0.0'

dependencies:
  dio:
    path: package_src
  http: ^0.12.0+1
  test: ^1.5.1
  test_coverage: ^0.2.0



